branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        require_code_owner_reviews: true
      required_status_checks:
        strict: true
        contexts: [build, test]
      enforce_admins: false
      restrictions:
        users: [mrtabaa, FaranakBaran]
      allow_force_pushes: false
      required_linear_history: true

  - name: release/*
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        require_code_owner_reviews: true
      required_status_checks:
        strict: true
      restrictions:
        users: [mrtabaa, FaranakBaran]
      allow_force_pushes: false
      required_linear_history: true

  - name: develop
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        require_code_owner_reviews: true
      required_status_checks:
        strict: true
      restrictions:
        users: [mrtabaa, FaranakBaran]
      allow_force_pushes: false
      required_linear_history: true
