# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Azure Web App - API

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'

  workflow_dispatch: # This line adds the manual trigger option

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'
          include-prerelease: true

      - name: dotnet publish
        run: dotnet publish ./backend/SepantaProject.sln -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'school-api'
          slot-name: 'Production'
          package: .
#          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2706DEB79BA64D12BFFB60412AC994FA }}
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6ADE688D43F2454A922DD09DFD14DEFC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9491EA51411E45E3991801662A644BFA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_12052D0712044E37AD3336D2A933C218 }}

  cleanup:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Clean up artifacts and publish directory
        uses: actions/checkout@v4
        with:
          clean: true
