name: Azure Web App - API

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Publish .NET App
        run: dotnet publish ./backend/SepantaProject.sln -c Release -o ./publish

      - name: Upload publish folder
        uses: actions/upload-artifact@v4
        with:
          name: publish-folder
          path: ./publish
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write   # keep OIDC here (this was in your old working yaml)
      contents: read

    steps:
      - name: Download publish folder
        uses: actions/download-artifact@v4
        with:
          name: publish-folder
          path: ./publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'wa-arshia-api-school'
          slot-name: 'Production'
          package: ./publish
