name: Angular Build & Test

on:
  pull_request:
    branches:
      - develop
      - release/*
    paths:
      - 'client/**'
      - '.github/workflows/ci-angular.yml'

jobs:
  angular-build-test:
    runs-on: ubuntu-latest
    name: Angular Build & Test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.1
          cache: 'npm'

      - name: Install dependencies
        working-directory: client
        run: npm ci --legacy-peer-deps

      - name: Run Angular unit tests
        working-directory: client
        run: npm run test -- --watch=false --browsers=ChromeHeadless

      - name: Build and Prerender Angular App (SSR)
        working-directory: client
        run: npx ng build --ssr
        env:
          NODE_OPTIONS: --max_old_space_size=8192
