name: .NET & Angular CI - Conditional

on:
  pull_request:
    branches:
      - develop
      - release/*

jobs:
  # -------------------------
  # 🔹 .NET Build & Test
  # -------------------------
  dotnet-build-test:
    name: .NET Build & Test
    runs-on: ubuntu-latest
    if: contains(toJson(github.event.pull_request.changed_files), 'backend/') || contains(github.event.pull_request.head.ref, 'backend')

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
          cache: true
          cache-dependency-path: backend/**/packages.lock.json

      - name: Restore dependencies
        working-directory: backend
        run: dotnet restore

      - name: Build solution
        working-directory: backend
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        working-directory: backend
        run: dotnet test --configuration Release --no-build --verbosity normal --logger "trx;LogFileName=test_results.trx"

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-test-results
          path: backend/TestResults

  # -------------------------
  # 🔹 Angular Build & Test
  # -------------------------
  angular-build-test:
    name: Angular Build & Test
    runs-on: ubuntu-latest
    if: contains(toJson(github.event.pull_request.changed_files), 'client/') || contains(github.event.pull_request.head.ref, 'client')

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.1
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - name: Install dependencies
        working-directory: client
        run: npm install --legacy-peer-deps

      # Uncomment to enable Angular tests
      # - name: Run Angular unit tests
      #   working-directory: client
      #   run: npm run test -- --watch=false --browsers=ChromeHeadless

      - name: Build and Prerender Angular App
        working-directory: client
        run: npx ng build --ssr
        env:
          NODE_OPTIONS: --max_old_space_size=8192
