name: Verify Settings App Sync

on:
  push:
    branches:
      - main
      - develop
      - release/*
  workflow_dispatch:

jobs:
  verify-settings:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check settings.yml presence
        run: |
          echo "Checking for .github/settings.yml..."
          if [ -f ".github/settings.yml" ]; then
            echo "✅ settings.yml found:"
            cat .github/settings.yml
          else
            echo "❌ settings.yml not found"
            exit 1
          fi

      - name: Print current branch protection status
        run: |
          echo "⚙️  Fetching branch protection info via GitHub CLI..."
          gh api repos/${{ github.repository }}/branches/main/protection || echo "❌ No protection found for main"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
